# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXPjeqGyyqKws-UVBVf_t6V94R5BiGNq
"""

import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions

# Загружаем данные из файла
input_file = 'data_multivar_nb.txt'
data = pd.read_csv(input_file, delimiter=',').values
X, y = data[:, :-1], data[:, -1].astype(int)

# Разделим данные на тренировочную и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

### Наивный байесовский классификатор
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred_nb = nb_classifier.predict(X_test)

# Оценка качества наивного байесовского классификатора
accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb, average="weighted")
recall_nb = recall_score(y_test, y_pred_nb, average="weighted")
f1_nb = f1_score(y_test, y_pred_nb, average="weighted")

print("Наивный Байесовский классификатор:")
print(f"Accuracy: {accuracy_nb:.2f}")
print(f"Precision: {precision_nb:.2f}")
print(f"Recall: {recall_nb:.2f}")
print(f"F1 Score: {f1_nb:.2f}")

# Визуализация работы наивного байесовского классификатора
plot_decision_regions(X_test, y_test, clf=nb_classifier, legend=2)
plt.title("Decision Boundary - Naive Bayes")
plt.show()

### Машина опорных векторов (SVM)
svm_classifier = SVC(kernel='linear', C=1)
svm_classifier.fit(X_train, y_train)
y_pred_svm = svm_classifier.predict(X_test)

# Оценка качества классификации для SVM
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm, average="weighted")
recall_svm = recall_score(y_test, y_pred_svm, average="weighted")
f1_svm = f1_score(y_test, y_pred_svm, average="weighted")

print("\nМашина опорных векторов (SVM):")
print(f"Accuracy: {accuracy_svm:.2f}")
print(f"Precision: {precision_svm:.2f}")
print(f"Recall: {recall_svm:.2f}")
print(f"F1 Score: {f1_svm:.2f}")

# Визуализация работы SVM
plot_decision_regions(X_test, y_test, clf=svm_classifier, legend=2)
plt.title("Decision Boundary - SVM")
plt.show()

### Сравнение результатов
print("\nСравнение моделей:")
print(f"Наивный Байес - Accuracy: {accuracy_nb:.2f}, Precision: {precision_nb:.2f}, Recall: {recall_nb:.2f}, F1 Score: {f1_nb:.2f}")
print(f"SVM - Accuracy: {accuracy_svm:.2f}, Precision: {precision_svm:.2f}, Recall: {recall_svm:.2f}, F1 Score: {f1_svm:.2f}")

# Вывод о том, какая модель лучше
if accuracy_svm > accuracy_nb:
    print("\nМодель SVM показала лучшие результаты по Accuracy. SVM лучше справляется с данной задачей.")
else:
    print("\nНаивный байесовский классификатор показал лучшие результаты по Accuracy. Наивный Байес лучше справляется с данной задачей.")

"""# Новый раздел"""