# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXPjeqGyyqKws-UVBVf_t6V94R5BiGNq
"""

import numpy as np
from sklearn import linear_model


# Визначимо зразок вхідних даних за допомогою двовимірних векторів і відповідних міток.
# Визначення зразка вхідних даних
X = np.array([[3.1, 7.2], [4, 6.7], [2.9, 8], [5.1, 4.5],
              [6, 5], [5.6, 5.1], [3.3, 0.4], [3.9, 0.9],
              [2.8, 1], [6.3, 1.6], [3.4, 4], [4.1, 4.9],
              [4, 4.5], [4.1, 0.6], [4.2, 4.9]])
y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3])

# Ми тренуватимемо класифікатор, використовуючи ці позначені дані.
# Створимо об'єкт логістичного класифікатора.
classifier = linear_model.LogisticRegression(solver='liblinear', C=1)

# Навчимо класифікатор, використовуючи певні дані.
classifier.fit(X, y)

# Візуалізуємо результати роботи класифікатора, відстеживши межі.
visualize_classifier(classifier, X, y)

"""# Новый раздел"""